NAME=wawpe_main

MASMPATH = c:\masm32

RC = $(MASMPATH)\bin\rc

Recource.res: Recource.rc
  $(RC) /i$(MASMPATH)\include Recource.rc

DocumentTypes.res: DocumentTypes.rc
  $(RC) /i$(MASMPATH)\include DocumentTypes.rc



